name: Deploy Next.js via Docker Compose

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build & Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          ports: 223
          script: |
            cd /root/docker/next-cicd
            docker pull ${{ secrets.DOCKER_USERNAME }}/portfolio-app:latest
            docker compose down
            docker compose up -d
